In [255]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [256]:
sample_sub = pd.read_csv("/content/sample_submission (6).csv")
sample_sub

     Patient ID  Heart Attack Risk
0       BMW7812                  0
1       XXM0972                  0
2       RQX1211                  0
3       RVN4963                  0
4       NCU1956                  0
...         ...                ...
1748    GQZ5013                  0
1749    FDK8693                  0
1750    SVO4635                  0
1751    KQR8949                  0
1752    XKA5925                  0

[1753 rows x 2 columns]

In [257]:
df_test = pd.read_csv("/content/test (2).csv")

df_test

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere
0,BMW7812,67,Male,208,158/88,72,0,0,1,0,...,9,6.615001,261404,31.251233,286,0,6,Argentina,South America,Southern Hemisphere
1,XXM0972,84,Male,220,131/68,107,0,0,1,1,...,4,10.543780,122093,22.221862,370,6,7,Japan,Asia,Northern Hemisphere
2,RQX1211,60,Male,145,160/98,71,1,0,1,0,...,8,5.994228,234966,29.162319,247,7,7,Canada,North America,Northern Hemisphere
3,RVN4963,45,Male,294,130/84,66,0,0,1,1,...,9,7.007392,216565,25.120605,360,4,6,France,Europe,Northern Hemisphere
4,NCU1956,36,Male,133,161/90,97,1,0,1,1,...,10,10.963544,223132,22.386804,605,5,10,Canada,North America,Northern Hemisphere
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1748,GQZ5013,81,Male,137,143/64,61,1,0,1,1,...,3,6.766948,50533,35.074391,191,3,10,Spain,Europe,Southern Hemisphere
1749,FDK8693,34,Female,304,102/92,93,0,1,0,1,...,10,6.900037,223874,22.418494,791,4,5,China,Asia,Northern Hemisphere
1750,SVO4635,75,Male,176,102/89,78,0,0,1,1,...,3,6.634988,228009,23.793280,748,5,8,Spain,Europe,Southern Hemisphere
1751,KQR8949,25,Male,307,137/94,78,0,1,1,0,...,3,10.516775,79211,33.469360,296,7,5,Spain,Europe,Southern Hemisphere
1752,XKA5925,47,Male,250,161/75,105,0,1,1,1,...,5,2.375214,36998,35.406146,527,4,4,Brazil,South America,Southern Hemisphere

In [258]:
df_train = pd.read_csv("/content/train.csv")

df_train

,Patient ID,Age,Sex,Cholesterol,Blood Pressure,Heart Rate,Diabetes,Family History,Smoking,Obesity,...,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Country,Continent,Hemisphere,Heart Attack Risk
0,RDG0550,33,Male,200,129/90,48,0,1,1,1,...,0.138443,184066,30.449815,63,6,7,Argentina,South America,Southern Hemisphere,1
1,NMA3851,56,Female,262,159/105,46,1,0,1,0,...,0.369552,211755,34.973685,333,7,8,Nigeria,Africa,Northern Hemisphere,1
2,TUI5807,19,Female,140,161/109,54,0,1,0,0,...,8.646334,252203,30.554246,537,2,10,Thailand,Asia,Northern Hemisphere,0
3,YYT5016,50,Female,163,120/62,53,0,1,1,1,...,1.107884,121954,35.390265,591,0,9,Spain,Europe,Southern Hemisphere,1
4,ZAC5937,89,Female,144,153/110,92,1,0,1,0,...,1.337570,180121,39.575483,145,2,5,Germany,Europe,Northern Hemisphere,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7005,BCB2291,29,Female,267,104/105,87,0,0,0,1,...,6.806894,236184,27.521246,598,4,5,France,Europe,Northern Hemisphere,0
7006,KIG5207,83,Male,296,134/99,77,1,1,1,1,...,3.015648,264390,21.332449,465,4,4,United Kingdom,Europe,Northern Hemisphere,0
7007,GCY1316,54,Male,120,134/84,103,1,1,1,1,...,4.825724,198358,37.465577,674,6,9,Colombia,South America,Northern Hemisphere,0
7008,RPK2629,42,Female,147,144/76,81,0,0,1,0,...,6.546390,202828,28.605789,623,7,10,Spain,Europe,Southern Hemisphere,1
7009,CWO3455,61,Male,176,172/60,56,0,1,1,0,...,6.651328,25823,22.057046,224,7,10,India,Asia,Northern Hemisphere,0

**Data Preprocessing**

In [259]:

df_test.describe()

,Age,Cholesterol,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day
count,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000,1753.000000
mean,54.498003,259.863092,74.684541,0.650314,0.497433,0.899030,0.507701,0.606959,10.154940,0.486594,0.491158,5.541358,5.992424,158334.493440,28.942447,421.256132,3.482031,7.018254
std,21.070471,81.499465,20.727584,0.477007,0.500136,0.301375,0.500083,0.488565,5.839031,0.499963,0.500064,2.865841,3.444605,80557.632883,6.307835,221.979158,2.289753,1.979261
min,18.000000,120.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008115,0.000000,0.000000,1.000000,0.003625,20443.000000,18.004211,30.000000,0.000000,4.000000
25%,36.000000,192.000000,56.000000,0.000000,0.000000,1.000000,0.000000,0.000000,4.819370,0.000000,0.000000,3.000000,3.100410,88117.000000,23.424618,239.000000,1.000000,5.000000
50%,54.000000,258.000000,75.000000,1.000000,0.000000,1.000000,1.000000,1.000000,10.497572,0.000000,0.000000,6.000000,5.916726,160257.000000,28.892801,423.000000,3.000000,7.000000
75%,73.000000,332.000000,92.000000,1.000000,1.000000,1.000000,1.000000,1.000000,15.212983,1.000000,1.000000,8.000000,9.021387,229490.000000,34.365926,610.000000,5.000000,9.000000
max,90.000000,400.000000,110.000000,1.000000,1.000000,1.000000,1.000000,1.000000,19.985813,1.000000,1.000000,10.000000,11.980970,299891.000000,39.997211,800.000000,7.000000,10.000000

In [260]:
df_train.describe()

,Age,Cholesterol,Heart Rate,Diabetes,Family History,Smoking,Obesity,Alcohol Consumption,Exercise Hours Per Week,Previous Heart Problems,Medication Use,Stress Level,Sedentary Hours Per Day,Income,BMI,Triglycerides,Physical Activity Days Per Week,Sleep Hours Per Day,Heart Attack Risk
count,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000,7010.00000,7010.000000,7010.000000,7010.000000,7010.000000,7010.000000
mean,53.510414,259.880742,75.105991,0.652782,0.491869,0.896291,0.499857,0.595863,9.979109,0.498146,0.500143,5.451783,5.994007,158245.34893,28.878692,416.782026,3.491583,7.024822,0.357204
std,21.290957,80.709248,20.507160,0.476120,0.499970,0.304904,0.500036,0.490759,5.769721,0.500032,0.500036,2.857989,3.472022,80585.31666,6.322401,224.195136,2.281077,1.990908,0.479210
min,18.000000,120.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002442,0.000000,0.000000,1.000000,0.001263,20062.00000,18.002337,30.000000,0.000000,4.000000,0.000000
25%,35.000000,192.000000,57.000000,0.000000,0.000000,1.000000,0.000000,0.000000,5.046024,0.000000,0.000000,3.000000,2.971831,88368.00000,23.422280,221.000000,2.000000,5.000000,0.000000
50%,53.000000,259.000000,75.000000,1.000000,0.000000,1.000000,0.000000,1.000000,9.982968,0.000000,1.000000,5.000000,5.936919,157378.50000,28.737627,416.000000,3.000000,7.000000,0.000000
75%,72.000000,329.000000,93.000000,1.000000,1.000000,1.000000,1.000000,1.000000,15.029659,1.000000,1.000000,8.000000,9.017592,227218.50000,34.321158,613.000000,5.000000,9.000000,1.000000
max,90.000000,400.000000,110.000000,1.000000,1.000000,1.000000,1.000000,1.000000,19.998709,1.000000,1.000000,10.000000,11.999313,299954.00000,39.993581,800.000000,7.000000,10.000000,1.000000

In [261]:
df_test.columns

Index(['Patient ID', 'Age', 'Sex', 'Cholesterol', 'Blood Pressure',
       'Heart Rate', 'Diabetes', 'Family History', 'Smoking', 'Obesity',
       'Alcohol Consumption', 'Exercise Hours Per Week', 'Diet',
       'Previous Heart Problems', 'Medication Use', 'Stress Level',
       'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides',
       'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'Country',
       'Continent', 'Hemisphere'],
      dtype='object')

In [262]:
df_train.columns

Index(['Patient ID', 'Age', 'Sex', 'Cholesterol', 'Blood Pressure',
       'Heart Rate', 'Diabetes', 'Family History', 'Smoking', 'Obesity',
       'Alcohol Consumption', 'Exercise Hours Per Week', 'Diet',
       'Previous Heart Problems', 'Medication Use', 'Stress Level',
       'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides',
       'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'Country',
       'Continent', 'Hemisphere', 'Heart Attack Risk'],
      dtype='object')

In [263]:
df_train.shape

(7010, 26)

In [264]:
df_test.shape

(1753, 25)

**Null Value Handling**

In [265]:
df_test.isnull().sum()

Patient ID                         0
Age                                0
Sex                                0
Cholesterol                        0
Blood Pressure                     0
Heart Rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Country                            0
Continent                          0
Hemisphere                         0
dtype: int64

In [266]:
df_train.isnull().sum()

Patient ID                         0
Age                                0
Sex                                0
Cholesterol                        0
Blood Pressure                     0
Heart Rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Country                            0
Continent                          0
Hemisphere                         0
Heart Attack Risk                  0
dtype: int64

In [267]:
  df_test = df_test.drop(['Patient ID', 'Blood Pressure'], axis=1)

  columns_to_standardize = ['Age', 'Cholesterol', 'Heart Rate', 'Exercise Hours Per Week',
                              'Stress Level', 'Sedentary Hours Per Day', 'Income', 'BMI',
                              'Triglycerides', 'Physical Activity Days Per Week', 'Sleep Hours Per Day']
  scaler = StandardScaler()
  df_test[columns_to_standardize] = scaler.fit_transform(df_test[columns_to_standardize])

  columns_to_encode = ['Sex', 'Diet', 'Country', 'Continent', 'Hemisphere']
  df_test = pd.get_dummies(df_test, columns=columns_to_encode, drop_first=True)

In [268]:
df_train = df_train.drop(['Patient ID', 'Blood Pressure'], axis=1)

columns_to_standardize = ['Age', 'Cholesterol', 'Heart Rate', 'Exercise Hours Per Week',
                              'Stress Level', 'Sedentary Hours Per Day', 'Income', 'BMI',
                              'Triglycerides', 'Physical Activity Days Per Week', 'Sleep Hours Per Day']
scaler = StandardScaler()
df_train[columns_to_standardize] = scaler.fit_transform(df_train[columns_to_standardize])

columns_to_encode = ['Sex', 'Diet', 'Country', 'Continent', 'Hemisphere']
df_train = pd.get_dummies(df_train, columns=columns_to_encode, drop_first=True)

In [269]:
train_df, val_df = train_test_split(df_train, test_size=0.2)

In [270]:
X_train = train_df.drop(['Heart Attack Risk'], axis=1)
y_train = train_df['Heart Attack Risk']

X_val = val_df.drop(['Heart Attack Risk'], axis=1)
y_val = val_df['Heart Attack Risk']

In [271]:
#import
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier

In [272]:
random = RandomForestClassifier(ccp_alpha=0.001, random_state=1, criterion='gini')
random.fit(X_train, y_train)
y_pred = random.predict(X_val)

y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [273]:
accuracy = accuracy_score(y_val, y_pred)
accuracy

0.6583452211126961

In [274]:

y_pred = random.predict(df_test)

y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [275]:

sample_sub['Heart Attack Risk'] = y_pred
sample_sub.head()

  Patient ID  Heart Attack Risk
0    BMW7812                  0
1    XXM0972                  0
2    RQX1211                  0
3    RVN4963                  0
4    NCU1956                  0

In [276]:
sample_sub.to_csv('submission.csv', index=False)

**Encoding**